name: Build test and deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
    - name: Install NPM modules
      run: npm install
    - name: Start BackEnd
      run: npm run start-be &
    - name: Start FrontEnd
      run: npm run start-fe &
    - name: Execute UI tests
      run: npm start test:ui
    
