name: Build test and deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - name: checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
    - name: Install NPM modules
      run: npm install
    - name: Replace the backend endpoint
      run: echo "export const settings = {host:\"http://localhost:3030\"}" > src/config.js
    - name: Start BackEnd
      run: npm run start-be &
    - name: Start FrontEnd
      run: npm run start-fe &
    - name: Install Browsers
      run: npx playwright install
    - name: Execute UI tests
      run: npm run test:ui

  deploy-be:
        needs: build_test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: JorgeLNJunior/render-deploy@v1.4.4
              with:
                service_id: ${{ secrets.MY_RENDER_SERVICE_ID_BE }}
                api_key: ${{ secrets.MY_RENDER_API_KEY }}
                wait_deploy: true 
    
  deploy-fe:
    needs: build_test
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: JorgeLNJunior/render-deploy@v1.4.4
          with:
            service_id: ${{ secrets.MY_RENDER_SERVICE_ID_FE }}
            api_key: ${{ secrets.MY_RENDER_API_KEY }}
            wait_deploy: true 
